using System.Text.RegularExpressions;
using Atlas.Domain.Workspaces;
using Atlas.Language.Abstractions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Atlas.Language.CSharp;

/// <summary>
/// Picks the methods most likely to encode business rules: decision density
/// (cyclomatic complexity), domain-flavoured names (Validate, Calculate,
/// Approve, Discount…), comparisons against literals, and thrown domain
/// exceptions — while skipping tests, generated code, migrations and DTOs.
/// Deterministic and cheap; the model only sees what this selects.
/// </summary>
public sealed partial class BusinessRuleCandidateSource : IBusinessRuleCandidateSource
{
    public const int MaxSnippetChars = 6_000;
    public const int MinComplexity = 3;

    [GeneratedRegex(@"(?i)(valid|calc|comput|price|pric|discount|tax|fee|rate|eligib|approv|authoriz|permit|allow|deny|limit|threshold|quota|rule|policy|penalt|interest|premium|coverage|claim|score|rank|status|transition|workflow|apply|process|check|verify|ensure|should|can|must|is[A-Z])")]
    private static partial Regex DomainName();

    [GeneratedRegex(@"(?i)(^|/)(test|tests|spec|specs|migrations|generated|obj|bin)(/|$)|\.(designer|g|generated|assemblyinfo|globalusings)\.cs$|\.(g|generated)\.i\.cs$|test[s]?\.cs$|\.migrations?/")]
    private static partial Regex SkipPath();

    public async Task<IReadOnlyList<BusinessRuleCandidate>> FindAsync(IArtifactReader workspace, int max, CancellationToken cancellationToken)
    {
        var scored = new List<BusinessRuleCandidate>();
        foreach (var relativePath in workspace.SourceFiles("*.cs"))
        {
            cancellationToken.ThrowIfCancellationRequested();
            if (SkipPath().IsMatch(relativePath))
            {
                continue;
            }

            string text;
            try
            {
                text = await workspace.ReadAllTextAsync(relativePath, cancellationToken);
            }
            catch (IOException)
            {
                continue;
            }

            if (text.Contains("<auto-generated", StringComparison.OrdinalIgnoreCase))
            {
                continue;
            }

            var tree = CSharpSyntaxTree.ParseText(text, path: relativePath, cancellationToken: cancellationToken);
            var root = await tree.GetRootAsync(cancellationToken);
            foreach (var method in root.DescendantNodes().OfType<BaseMethodDeclarationSyntax>())
            {
                if (method.Body is null && method.ExpressionBody is null)
                {
                    continue;
                }

                var candidate = Score(relativePath, method);
                if (candidate is not null)
                {
                    scored.Add(candidate);
                }
            }
        }

        return scored
            .OrderByDescending(c => c.Score)
            .ThenBy(c => c.FilePath, StringComparer.Ordinal)
            .ThenBy(c => c.StartLine)
            .Take(Math.Max(1, max))
            .ToList();
    }

    internal static BusinessRuleCandidate? Score(string relativePath, BaseMethodDeclarationSyntax method)
    {
        var complexity = CyclomaticComplexityWalker.Measure(method);
        var symbol = CSharpLanguageAnalyzer.MethodSymbol(method);
        var type = method.Ancestors().OfType<BaseTypeDeclarationSyntax>().FirstOrDefault();
        var typeName = type?.Identifier.Text ?? "";
        var methodName = method is MethodDeclarationSyntax m ? m.Identifier.Text : symbol;

        // Plumbing signals: getters/setters-only types, mappers, configuration.
        if (typeName.EndsWith("Dto", StringComparison.Ordinal) || typeName.EndsWith("ViewModel", StringComparison.Ordinal)
            || typeName.EndsWith("Mapper", StringComparison.Ordinal) || typeName.EndsWith("Profile", StringComparison.Ordinal)
            || typeName.EndsWith("Startup", StringComparison.Ordinal) || typeName == "Program")
        {
            return null;
        }

        var body = method.ToString();
        var literalComparisons = method.DescendantNodes().OfType<BinaryExpressionSyntax>()
            .Count(b => (b.IsKind(SyntaxKind.GreaterThanExpression) || b.IsKind(SyntaxKind.GreaterThanOrEqualExpression)
                         || b.IsKind(SyntaxKind.LessThanExpression) || b.IsKind(SyntaxKind.LessThanOrEqualExpression)
                         || b.IsKind(SyntaxKind.EqualsExpression) || b.IsKind(SyntaxKind.NotEqualsExpression))
                        && (b.Left is LiteralExpressionSyntax || b.Right is LiteralExpressionSyntax));
        var throws = method.DescendantNodes().OfType<ThrowStatementSyntax>().Count() + method.DescendantNodes().OfType<ThrowExpressionSyntax>().Count();
        var domainName = DomainName().IsMatch(methodName) || DomainName().IsMatch(typeName);
        var arithmetic = method.DescendantNodes().OfType<BinaryExpressionSyntax>()
            .Count(b => b.IsKind(SyntaxKind.MultiplyExpression) || b.IsKind(SyntaxKind.DivideExpression) || b.IsKind(SyntaxKind.AddExpression) || b.IsKind(SyntaxKind.SubtractExpression));

        var score = complexity
                    + literalComparisons * 1.5
                    + throws * 1.0
                    + Math.Min(arithmetic, 6) * 0.5
                    + (domainName ? 4 : 0);

        if (complexity < MinComplexity && !(domainName && (literalComparisons > 0 || throws > 0)))
        {
            return null;
        }

        var span = method.GetLocation().GetLineSpan();
        var snippet = body.Length > MaxSnippetChars ? body[..MaxSnippetChars] + "\n// … truncated …" : body;
        return new BusinessRuleCandidate(
            relativePath,
            symbol,
            span.StartLinePosition.Line + 1,
            span.EndLinePosition.Line + 1,
            complexity,
            Math.Round(score, 2),
            snippet);
    }
}
