// <auto-generated />
using System;
using Atlas.Governance.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Atlas.Governance.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GovernanceDbContext))]
    [Migration("20260907014712_AddUsageFacts")]
    partial class AddUsageFacts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("governance")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Atlas.Governance.Domain.CostFact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("amount");

                    b.Property<string>("Basis")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("basis");

                    b.Property<DateTimeOffset>("CollectedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("collected_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Detail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("detail");

                    b.Property<string>("Dimension")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("dimension");

                    b.Property<string>("DimensionKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("dimension_key");

                    b.Property<DateOnly>("Period")
                        .HasColumnType("date")
                        .HasColumnName("period");

                    b.Property<string>("PriceCatalogVersion")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("price_catalog_version");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("provider");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Unit")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("unit");

                    b.HasKey("Id")
                        .HasName("pk_cost_facts");

                    b.HasIndex("SourceId", "Period")
                        .HasDatabaseName("ix_cost_facts_source_id_period");

                    b.HasIndex("TenantId", "Period")
                        .HasDatabaseName("ix_cost_facts_tenant_id_period");

                    b.ToTable("cost_facts", "governance");
                });

            modelBuilder.Entity("Atlas.Governance.Domain.CostSource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CredentialName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("credential_name");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<DateTimeOffset?>("LastSyncAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sync_at_utc");

                    b.Property<string>("LastSyncError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("last_sync_error");

                    b.Property<int>("LastSyncFacts")
                        .HasColumnType("integer")
                        .HasColumnName("last_sync_facts");

                    b.Property<string>("LastSyncStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("last_sync_status");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("provider");

                    b.Property<string>("Scope")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("scope");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_cost_sources");

                    b.HasIndex("TenantId", "Provider")
                        .IsUnique()
                        .HasDatabaseName("ix_cost_sources_tenant_id_provider");

                    b.ToTable("cost_sources", "governance");
                });

            modelBuilder.Entity("Atlas.Governance.Domain.SeatFact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CollectedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("collected_at_utc");

                    b.Property<DateTimeOffset?>("LastActivityAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at_utc");

                    b.Property<bool>("PendingCancellation")
                        .HasColumnType("boolean")
                        .HasColumnName("pending_cancellation");

                    b.Property<string>("Plan")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("plan");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("provider");

                    b.Property<string>("SeatKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("seat_key");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_seat_facts");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_seat_facts_tenant_id");

                    b.HasIndex("SourceId", "SeatKey")
                        .IsUnique()
                        .HasDatabaseName("ix_seat_facts_source_id_seat_key");

                    b.ToTable("seat_facts", "governance");
                });

            modelBuilder.Entity("Atlas.Governance.Domain.UsageFact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("actor");

                    b.Property<long>("CacheReadTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("cache_read_tokens");

                    b.Property<long>("CacheWriteTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("cache_write_tokens");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<decimal?>("EstimatedCost")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("estimated_cost");

                    b.Property<long>("InputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("input_tokens");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("model");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("output_tokens");

                    b.Property<DateOnly>("Period")
                        .HasColumnType("date")
                        .HasColumnName("period");

                    b.Property<string>("PriceCatalogVersion")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("price_catalog_version");

                    b.Property<DateTimeOffset>("ReportedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reported_at_utc");

                    b.Property<int>("Requests")
                        .HasColumnType("integer")
                        .HasColumnName("requests");

                    b.Property<int>("Sessions")
                        .HasColumnType("integer")
                        .HasColumnName("sessions");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("source");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Tool")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("tool");

                    b.HasKey("Id")
                        .HasName("pk_usage_facts");

                    b.HasIndex("TenantId", "Period")
                        .HasDatabaseName("ix_usage_facts_tenant_id_period");

                    b.HasIndex("TenantId", "Actor", "Tool", "Period", "Model")
                        .IsUnique()
                        .HasDatabaseName("ix_usage_facts_tenant_id_actor_tool_period_model");

                    b.ToTable("usage_facts", "governance");
                });
#pragma warning restore 612, 618
        }
    }
}
