// <auto-generated />
namespace Shop.Web
{
    public partial class Default
    {
        protected global::System.Web.UI.WebControls.Label lblUser;
        public string Cpf { get; set; } // generated noise: excluded by .atlasignore
    }
}
