using System.Text;
using Atlas.Domain.Workspaces;
using Atlas.Language.CSharp;

namespace Atlas.Language.Tests;

public class BusinessRuleCandidateSourceTests
{
    private sealed class MemoryReader(Dictionary<string, string> files) : IArtifactReader
    {
        public string RootPath => "/mem";

        public IEnumerable<string> EnumerateFiles(string searchPattern) => files.Keys.Where(k => k.EndsWith(searchPattern.TrimStart('*'), StringComparison.Ordinal));

        public Task<string> ReadAllTextAsync(string relativePath, CancellationToken cancellationToken) => Task.FromResult(files[relativePath]);

        public Stream OpenRead(string relativePath) => new MemoryStream(Encoding.UTF8.GetBytes(files[relativePath]));
    }

    private const string Pricing = """
        namespace Shop;
        public class PricingService
        {
            public decimal CalculateDiscount(Order order)
            {
                if (order.Customer.IsVip && order.Total > 1000m) return order.Total * 0.15m;
                if (order.Items.Count > 10) return order.Total * 0.05m;
                if (order.Coupon is not null && order.Coupon.ExpiresAt > DateTime.UtcNow) return order.Coupon.Amount;
                return 0m;
            }

            public string Name => "pricing";
        }
        """;

    private const string Plumbing = """
        namespace Shop;
        public class OrderDto { public int Id { get; set; } public string ToJson() { return System.Text.Json.JsonSerializer.Serialize(this); } }
        public class OrderMapper { public OrderDto Map(Order o) { if (o is null) return null; return new OrderDto { Id = o.Id }; } }
        """;

    private const string Approval = """
        namespace Shop;
        public class LoanApproval
        {
            public void Approve(Loan loan)
            {
                if (loan.Amount > 50000) throw new DomainException("Loans above 50k need a manager.");
                if (loan.Applicant.Score < 600) throw new DomainException("Score too low.");
            }
        }
        """;

    [Fact]
    public async Task Ranks_decision_heavy_domain_methods_first_and_skips_plumbing_tests_and_generated_code()
    {
        var files = new Dictionary<string, string>
        {
            ["src/Shop/PricingService.cs"] = Pricing,
            ["src/Shop/Dto.cs"] = Plumbing,
            ["src/Shop/LoanApproval.cs"] = Approval,
            ["tests/Shop.Tests/PricingTests.cs"] = Pricing,
            ["src/Shop/Migrations/20240101_Init.cs"] = Pricing,
            ["src/Shop/Generated.g.cs"] = Pricing,
            ["src/Shop/Auto.cs"] = "// <auto-generated />\n" + Pricing,
        };

        var candidates = await new BusinessRuleCandidateSource().FindAsync(new MemoryReader(files), 10, CancellationToken.None);

        Assert.Equal(2, candidates.Count);
        Assert.Equal("PricingService.CalculateDiscount", candidates[0].Symbol);
        Assert.Equal("LoanApproval.Approve", candidates[1].Symbol);
        Assert.Equal("src/Shop/PricingService.cs", candidates[0].FilePath);
        Assert.Equal(4, candidates[0].StartLine);
        Assert.Contains("order.Total * 0.15m", candidates[0].Snippet);
        Assert.True(candidates[0].Complexity >= 5);
        Assert.DoesNotContain(candidates, c => c.FilePath.Contains("Dto") || c.FilePath.Contains("tests/") || c.FilePath.Contains("Migrations") || c.FilePath.EndsWith(".g.cs") || c.FilePath.EndsWith("Auto.cs"));
    }

    [Fact]
    public async Task Honours_the_maximum_and_truncates_huge_methods()
    {
        var huge = new StringBuilder("namespace X; public class Calc { public int Compute(int a) { var r = 0;\n");
        for (var i = 0; i < 600; i++)
        {
            huge.AppendLine($"        if (a > {i}) r += {i}; // padding line to make the method long");
        }

        huge.AppendLine("        return r; } }");
        var files = new Dictionary<string, string> { ["src/Calc.cs"] = huge.ToString(), ["src/Pricing.cs"] = Pricing };

        var candidates = await new BusinessRuleCandidateSource().FindAsync(new MemoryReader(files), 1, CancellationToken.None);

        Assert.Single(candidates);
        Assert.Equal("Calc.Compute", candidates[0].Symbol);
        Assert.True(candidates[0].Snippet.Length <= BusinessRuleCandidateSource.MaxSnippetChars + 40);
        Assert.EndsWith("// … truncated …", candidates[0].Snippet);
    }
}
