<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="10.0.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageReference Include="NetArchTest.Rules" Version="1.3.2" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Atlas.Api\Atlas.Api.csproj" />
    <ProjectReference Include="..\..\src\Atlas.Worker\Atlas.Worker.csproj" />
    <ProjectReference Include="..\..\src\Atlas.Scanner.Runtime\Atlas.Scanner.Runtime.csproj" />
    <ProjectReference Include="..\..\src\Atlas.Connector.Local\Atlas.Connector.Local.csproj" />
    <ProjectReference Include="..\..\src\Atlas.Connector.Git\Atlas.Connector.Git.csproj" />
    <ProjectReference Include="..\..\src\Atlas.Language.CSharp\Atlas.Language.CSharp.csproj" />
    <ProjectReference Include="..\..\src\Atlas.Scanner.Dependencies\Atlas.Scanner.Dependencies.csproj" />
    <ProjectReference Include="..\..\src\Atlas.Scanner.Secrets\Atlas.Scanner.Secrets.csproj" />
    <ProjectReference Include="..\..\src\Atlas.Scanner.Security\Atlas.Scanner.Security.csproj" />
    <ProjectReference Include="..\..\src\Atlas.Reporting\Atlas.Reporting.csproj" />
    <ProjectReference Include="..\..\src\Atlas.Scanner.Quality\Atlas.Scanner.Quality.csproj" />
    <ProjectReference Include="..\..\src\Atlas.Scanner.Architecture\Atlas.Scanner.Architecture.csproj" />
  </ItemGroup>

</Project>