// <auto-generated />
using System;
using Atlas.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Atlas.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AtlasDbContext))]
    [Migration("20260829152346_AddRuleLocalizations")]
    partial class AddRuleLocalizations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("atlas")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Atlas.Domain.Assessments.Assessment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Branch")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("branch");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_kind");

                    b.Property<string>("SourceLocator")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("source_locator");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_assessments");

                    b.HasIndex("TenantId", "CreatedAtUtc")
                        .HasDatabaseName("ix_assessments_tenant_id_created_at_utc");

                    b.ToTable("assessments", "atlas");
                });

            modelBuilder.Entity("Atlas.Domain.Assessments.AssessmentRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assessment_id");

                    b.Property<string>("CommitSha")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("commit_sha");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("failure_reason");

                    b.Property<int>("FindingsNew")
                        .HasColumnType("integer")
                        .HasColumnName("findings_new");

                    b.Property<int>("FindingsRecurring")
                        .HasColumnType("integer")
                        .HasColumnName("findings_recurring");

                    b.Property<int>("FindingsRegressed")
                        .HasColumnType("integer")
                        .HasColumnName("findings_regressed");

                    b.Property<int>("FindingsResolved")
                        .HasColumnType("integer")
                        .HasColumnName("findings_resolved");

                    b.Property<DateTimeOffset?>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at_utc");

                    b.Property<int?>("HealthScore")
                        .HasColumnType("integer")
                        .HasColumnName("health_score");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<int?>("OpenFindings")
                        .HasColumnType("integer")
                        .HasColumnName("open_findings");

                    b.Property<int>("ScannersFailed")
                        .HasColumnType("integer")
                        .HasColumnName("scanners_failed");

                    b.Property<int>("ScannersRun")
                        .HasColumnType("integer")
                        .HasColumnName("scanners_run");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_assessment_runs");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_assessment_runs_tenant_id");

                    b.HasIndex("AssessmentId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_assessment_runs_assessment_id_number");

                    b.ToTable("assessment_runs", "atlas");
                });

            modelBuilder.Entity("Atlas.Domain.Assessments.InventorySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assessment_id");

                    b.Property<double>("AverageCyclomaticComplexity")
                        .HasColumnType("double precision")
                        .HasColumnName("average_cyclomatic_complexity");

                    b.Property<string>("CommitSha")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("commit_sha");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("FileCount")
                        .HasColumnType("integer")
                        .HasColumnName("file_count");

                    b.Property<string>("LanguageId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("language_id");

                    b.Property<int>("MaxCyclomaticComplexity")
                        .HasColumnType("integer")
                        .HasColumnName("max_cyclomatic_complexity");

                    b.Property<int>("MethodCount")
                        .HasColumnType("integer")
                        .HasColumnName("method_count");

                    b.Property<int>("ProjectCount")
                        .HasColumnType("integer")
                        .HasColumnName("project_count");

                    b.Property<string>("ProjectsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("projects_json");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<int>("SolutionCount")
                        .HasColumnType("integer")
                        .HasColumnName("solution_count");

                    b.Property<double?>("SymbolResolutionRate")
                        .HasColumnType("double precision")
                        .HasColumnName("symbol_resolution_rate");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TierAchieved")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("tier_achieved");

                    b.Property<long>("TotalLines")
                        .HasColumnType("bigint")
                        .HasColumnName("total_lines");

                    b.Property<int>("TypeCount")
                        .HasColumnType("integer")
                        .HasColumnName("type_count");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_inventory_snapshots");

                    b.HasIndex("RunId")
                        .HasDatabaseName("ix_inventory_snapshots_run_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_inventory_snapshots_tenant_id");

                    b.HasIndex("AssessmentId", "LanguageId", "CreatedAtUtc")
                        .HasDatabaseName("ix_inventory_snapshots_assessment_id_language_id_created_at_utc");

                    b.ToTable("inventory_snapshots", "atlas");
                });

            modelBuilder.Entity("Atlas.Domain.Findings.Finding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assessment_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("fingerprint");

                    b.Property<Guid>("FirstSeenScanId")
                        .HasColumnType("uuid")
                        .HasColumnName("first_seen_scan_id");

                    b.Property<Guid>("LastSeenScanId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_seen_scan_id");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("origin");

                    b.Property<Guid?>("ResolvedScanId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_scan_id");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("rule_id");

                    b.Property<int>("Severity")
                        .HasColumnType("integer")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_findings");

                    b.HasIndex("RuleId")
                        .HasDatabaseName("ix_findings_rule_id");

                    b.HasIndex("AssessmentId", "RuleId", "Status")
                        .HasDatabaseName("ix_findings_assessment_id_rule_id_status");

                    b.HasIndex("TenantId", "AssessmentId", "Fingerprint")
                        .IsUnique()
                        .HasDatabaseName("ix_findings_tenant_id_assessment_id_fingerprint");

                    b.ToTable("findings", "atlas");
                });

            modelBuilder.Entity("Atlas.Domain.Findings.FindingOccurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("data_json");

                    b.Property<Guid>("FindingId")
                        .HasColumnType("uuid")
                        .HasColumnName("finding_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("message");

                    b.Property<string>("Remediation")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("remediation");

                    b.Property<Guid>("ScanId")
                        .HasColumnType("uuid")
                        .HasColumnName("scan_id");

                    b.Property<int>("Severity")
                        .HasColumnType("integer")
                        .HasColumnName("severity");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_finding_occurrences");

                    b.HasIndex("ScanId")
                        .HasDatabaseName("ix_finding_occurrences_scan_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_finding_occurrences_tenant_id");

                    b.HasIndex("FindingId", "CreatedAtUtc")
                        .HasDatabaseName("ix_finding_occurrences_finding_id_created_at_utc");

                    b.ToTable("finding_occurrences", "atlas");
                });

            modelBuilder.Entity("Atlas.Domain.Health.HealthSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assessment_id");

                    b.Property<string>("CommitSha")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("commit_sha");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DimensionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("dimensions_json");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("explanation");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("model_version");

                    b.Property<int>("OpenFindings")
                        .HasColumnType("integer")
                        .HasColumnName("open_findings");

                    b.Property<int>("ProjectCount")
                        .HasColumnType("integer")
                        .HasColumnName("project_count");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("risk_level");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_health_snapshots");

                    b.HasIndex("RunId")
                        .HasDatabaseName("ix_health_snapshots_run_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_health_snapshots_tenant_id");

                    b.HasIndex("AssessmentId", "CreatedAtUtc")
                        .HasDatabaseName("ix_health_snapshots_assessment_id_created_at_utc");

                    b.ToTable("health_snapshots", "atlas");
                });

            modelBuilder.Entity("Atlas.Domain.Jobs.ScanJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assessment_id");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer")
                        .HasColumnName("attempt");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at_utc");

                    b.Property<DateTimeOffset?>("LeaseExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at_utc");

                    b.Property<string>("LeasedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("leased_by");

                    b.Property<DateTimeOffset>("QueuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("queued_at_utc");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_scan_jobs");

                    b.HasIndex("AssessmentId")
                        .HasDatabaseName("ix_scan_jobs_assessment_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_scan_jobs_tenant_id");

                    b.HasIndex("State", "QueuedAtUtc")
                        .HasDatabaseName("ix_scan_jobs_state_queued_at_utc");

                    b.ToTable("scan_jobs", "atlas");
                });

            modelBuilder.Entity("Atlas.Domain.Rules.RuleDefinition", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("category");

                    b.Property<string>("DefaultSeverity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("default_severity");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<string>("LocalizationsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("localizations_json");

                    b.Property<string>("Remediation")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("remediation");

                    b.Property<string>("ScannerId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("scanner_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_rule_definitions");

                    b.ToTable("rule_definitions", "atlas");
                });

            modelBuilder.Entity("Atlas.Domain.Scans.Scan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assessment_id");

                    b.Property<string>("CommitSha")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("commit_sha");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error");

                    b.Property<int>("FindingsEmitted")
                        .HasColumnType("integer")
                        .HasColumnName("findings_emitted");

                    b.Property<int>("FindingsNew")
                        .HasColumnType("integer")
                        .HasColumnName("findings_new");

                    b.Property<int>("FindingsRecurring")
                        .HasColumnType("integer")
                        .HasColumnName("findings_recurring");

                    b.Property<int>("FindingsRegressed")
                        .HasColumnType("integer")
                        .HasColumnName("findings_regressed");

                    b.Property<int>("FindingsResolved")
                        .HasColumnType("integer")
                        .HasColumnName("findings_resolved");

                    b.Property<DateTimeOffset?>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at_utc");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("ScannerId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("scanner_id");

                    b.Property<string>("ScannerVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("scanner_version");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_scans");

                    b.HasIndex("RunId")
                        .HasDatabaseName("ix_scans_run_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_scans_tenant_id");

                    b.HasIndex("AssessmentId", "ScannerId", "CommitSha", "Status")
                        .HasDatabaseName("ix_scans_assessment_id_scanner_id_commit_sha_status");

                    b.ToTable("scans", "atlas");
                });

            modelBuilder.Entity("Atlas.Domain.Tenants.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.ToTable("tenants", "atlas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Default"
                        });
                });

            modelBuilder.Entity("Atlas.Domain.Workspaces.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Branch")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("branch");

                    b.Property<string>("CommitSha")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("commit_sha");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("failure_reason");

                    b.Property<bool>("IsBorrowed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_borrowed");

                    b.Property<DateTimeOffset>("LeaseExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at_utc");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("root_path");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_kind");

                    b.Property<string>("SourceLocator")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("source_locator");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_workspaces");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_workspaces_tenant_id");

                    b.HasIndex("State", "LeaseExpiresAtUtc")
                        .HasDatabaseName("ix_workspaces_state_lease_expires_at_utc");

                    b.ToTable("workspaces", "atlas");
                });

            modelBuilder.Entity("Atlas.Domain.Assessments.Assessment", b =>
                {
                    b.HasOne("Atlas.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assessments_tenants_tenant_id");
                });

            modelBuilder.Entity("Atlas.Domain.Assessments.AssessmentRun", b =>
                {
                    b.HasOne("Atlas.Domain.Assessments.Assessment", null)
                        .WithMany()
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assessment_runs_assessments_assessment_id");

                    b.HasOne("Atlas.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assessment_runs_tenants_tenant_id");
                });

            modelBuilder.Entity("Atlas.Domain.Assessments.InventorySnapshot", b =>
                {
                    b.HasOne("Atlas.Domain.Assessments.Assessment", null)
                        .WithMany()
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_snapshots_assessments_assessment_id");

                    b.HasOne("Atlas.Domain.Assessments.AssessmentRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .HasConstraintName("fk_inventory_snapshots_assessment_runs_run_id");

                    b.HasOne("Atlas.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_snapshots_tenants_tenant_id");
                });

            modelBuilder.Entity("Atlas.Domain.Findings.Finding", b =>
                {
                    b.HasOne("Atlas.Domain.Assessments.Assessment", null)
                        .WithMany()
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_findings_assessments_assessment_id");

                    b.HasOne("Atlas.Domain.Rules.RuleDefinition", null)
                        .WithMany()
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_findings_rule_definitions_rule_id");

                    b.HasOne("Atlas.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_findings_tenants_tenant_id");
                });

            modelBuilder.Entity("Atlas.Domain.Findings.FindingOccurrence", b =>
                {
                    b.HasOne("Atlas.Domain.Findings.Finding", null)
                        .WithMany()
                        .HasForeignKey("FindingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_finding_occurrences_findings_finding_id");

                    b.HasOne("Atlas.Domain.Scans.Scan", null)
                        .WithMany()
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_finding_occurrences_scans_scan_id");

                    b.HasOne("Atlas.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_finding_occurrences_tenants_tenant_id");

                    b.OwnsOne("Atlas.Domain.Findings.Evidence", "Evidence", b1 =>
                        {
                            b1.Property<Guid>("FindingOccurrenceId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("FilePath")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("evidence_file_path");

                            b1.Property<int?>("LineEnd")
                                .HasColumnType("integer")
                                .HasColumnName("evidence_line_end");

                            b1.Property<int?>("LineStart")
                                .HasColumnType("integer")
                                .HasColumnName("evidence_line_start");

                            b1.Property<string>("ScannerId")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("evidence_scanner_id");

                            b1.Property<string>("ScannerVersion")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("evidence_scanner_version");

                            b1.Property<string>("SnippetHash")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("evidence_snippet_hash");

                            b1.Property<string>("Symbol")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("evidence_symbol");

                            b1.HasKey("FindingOccurrenceId");

                            b1.ToTable("finding_occurrences", "atlas");

                            b1.WithOwner()
                                .HasForeignKey("FindingOccurrenceId")
                                .HasConstraintName("fk_finding_occurrences_finding_occurrences_id");
                        });

                    b.Navigation("Evidence")
                        .IsRequired();
                });

            modelBuilder.Entity("Atlas.Domain.Health.HealthSnapshot", b =>
                {
                    b.HasOne("Atlas.Domain.Assessments.Assessment", null)
                        .WithMany()
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_health_snapshots_assessments_assessment_id");

                    b.HasOne("Atlas.Domain.Assessments.AssessmentRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .HasConstraintName("fk_health_snapshots_assessment_runs_run_id");

                    b.HasOne("Atlas.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_health_snapshots_tenants_tenant_id");
                });

            modelBuilder.Entity("Atlas.Domain.Jobs.ScanJob", b =>
                {
                    b.HasOne("Atlas.Domain.Assessments.Assessment", null)
                        .WithMany()
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scan_jobs_assessments_assessment_id");

                    b.HasOne("Atlas.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scan_jobs_tenants_tenant_id");
                });

            modelBuilder.Entity("Atlas.Domain.Scans.Scan", b =>
                {
                    b.HasOne("Atlas.Domain.Assessments.Assessment", null)
                        .WithMany()
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scans_assessments_assessment_id");

                    b.HasOne("Atlas.Domain.Assessments.AssessmentRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .HasConstraintName("fk_scans_assessment_runs_run_id");

                    b.HasOne("Atlas.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scans_tenants_tenant_id");
                });

            modelBuilder.Entity("Atlas.Domain.Workspaces.Workspace", b =>
                {
                    b.HasOne("Atlas.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workspaces_tenants_tenant_id");
                });
#pragma warning restore 612, 618
        }
    }
}
