// <auto-generated />
using System;
using Atlas.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Atlas.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AtlasDbContext))]
    [Migration("20260831030021_AddTenantNotificationSettings")]
    partial class AddTenantNotificationSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("atlas")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Atlas.Domain.Ai.AiNarrative", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assessment_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("FeedbackComment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("feedback_comment");

                    b.Property<long>("InputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("input_tokens");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("kind");

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("lang");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("model");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("output_tokens");

                    b.Property<DateTimeOffset?>("RatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rated_at_utc");

                    b.Property<string>("RatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("rated_by");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_ai_narratives");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_ai_narratives_tenant_id");

                    b.HasIndex("AssessmentId", "Kind", "Key", "Lang")
                        .IsUnique()
                        .HasDatabaseName("ix_ai_narratives_assessment_id_kind_key_lang");

                    b.ToTable("ai_narratives", "atlas");
                });

            modelBuilder.Entity("Atlas.Domain.Ai.AiProviderSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("base_url");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<byte[]>("KeyEnvelope")
                        .HasColumnType("bytea")
                        .HasColumnName("key_envelope");

                    b.Property<string>("LastTestMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("last_test_message");

                    b.Property<bool?>("LastTestSucceeded")
                        .HasColumnType("boolean")
                        .HasColumnName("last_test_succeeded");

                    b.Property<DateTimeOffset?>("LastTestedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_tested_at_utc");

                    b.Property<int>("MaxSnippetsPerAnalysis")
                        .HasColumnType("integer")
                        .HasColumnName("max_snippets_per_analysis");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("model");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("provider");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_ai_provider_settings");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_ai_provider_settings_tenant_id");

                    b.ToTable("ai_provider_settings", "atlas");
                });

            modelBuilder.Entity("Atlas.Domain.Ai.BusinessRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_id");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assessment_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("category");

                    b.Property<string>("ConditionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("conditions_json");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description_en");

                    b.Property<string>("DescriptionPt")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description_pt");

                    b.Property<string>("FeedbackComment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("feedback_comment");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("file_path");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("RatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rated_at_utc");

                    b.Property<string>("RatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("rated_by");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<int>("StartLine")
                        .HasColumnType("integer")
                        .HasColumnName("start_line");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("symbol");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_business_rules");

                    b.HasIndex("AnalysisId")
                        .HasDatabaseName("ix_business_rules_analysis_id");

                    b.HasIndex("AssessmentId")
                        .HasDatabaseName("ix_business_rules_assessment_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_business_rules_tenant_id");

                    b.ToTable("business_rules", "atlas");
                });

            modelBuilder.Entity("Atlas.Domain.Ai.BusinessRuleAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assessment_id");

                    b.Property<int>("CandidatesFound")
                        .HasColumnType("integer")
                        .HasColumnName("candidates_found");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error");

                    b.Property<long>("InputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("input_tokens");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("model");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("output_tokens");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("provider");

                    b.Property<int>("RulesFound")
                        .HasColumnType("integer")
                        .HasColumnName("rules_found");

                    b.Property<int>("SnippetsSent")
                        .HasColumnType("integer")
                        .HasColumnName("snippets_sent");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_business_rule_analyses");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_business_rule_analyses_tenant_id");

                    b.HasIndex("AssessmentId", "StartedAtUtc")
                        .HasDatabaseName("ix_business_rule_analyses_assessment_id_started_at_utc");

                    b.ToTable("business_rule_analyses", "atlas");
                });

            modelBuilder.Entity("Atlas.Domain.Assessments.Assessment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Branch")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("branch");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CredentialName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("credential_name");

                    b.Property<string>("ExcludeGlobsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("exclude_globs_json");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int?>("RerunEveryDays")
                        .HasColumnType("integer")
                        .HasColumnName("rerun_every_days");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_kind");

                    b.Property<string>("SourceLocator")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("source_locator");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("TagsJson")
                        .HasColumnType("text")
                        .HasColumnName("tags_json");

                    b.Property<DateTimeOffset?>("TargetDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("target_date");

                    b.Property<int?>("TargetScore")
                        .HasColumnType("integer")
                        .HasColumnName("target_score");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("WebhookUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("webhook_url");

                    b.HasKey("Id")
                        .HasName("pk_assessments");

                    b.HasIndex("TenantId", "CreatedAtUtc")
                        .HasDatabaseName("ix_assessments_tenant_id_created_at_utc");

                    b.ToTable("assessments", "atlas");
                });

            modelBuilder.Entity("Atlas.Domain.Assessments.AssessmentAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assessment_id");

                    b.Property<DateTimeOffset>("GrantedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at_utc");

                    b.Property<string>("GrantedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("granted_by");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subject");

                    b.Property<string>("SubjectName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subject_name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_assessment_access");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_assessment_access_tenant_id");

                    b.HasIndex("AssessmentId", "Subject")
                        .IsUnique()
                        .HasDatabaseName("ix_assessment_access_assessment_id_subject");

                    b.ToTable("assessment_access", "atlas");
                });

            modelBuilder.Entity("Atlas.Domain.Assessments.AssessmentRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assessment_id");

                    b.Property<string>("CommitSha")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("commit_sha");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("failure_reason");

                    b.Property<int>("FindingsNew")
                        .HasColumnType("integer")
                        .HasColumnName("findings_new");

                    b.Property<int>("FindingsRecurring")
                        .HasColumnType("integer")
                        .HasColumnName("findings_recurring");

                    b.Property<int>("FindingsRegressed")
                        .HasColumnType("integer")
                        .HasColumnName("findings_regressed");

                    b.Property<int>("FindingsResolved")
                        .HasColumnType("integer")
                        .HasColumnName("findings_resolved");

                    b.Property<DateTimeOffset?>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at_utc");

                    b.Property<int?>("HealthScore")
                        .HasColumnType("integer")
                        .HasColumnName("health_score");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<int?>("OpenFindings")
                        .HasColumnType("integer")
                        .HasColumnName("open_findings");

                    b.Property<int>("ScannersFailed")
                        .HasColumnType("integer")
                        .HasColumnName("scanners_failed");

                    b.Property<int>("ScannersRun")
                        .HasColumnType("integer")
                        .HasColumnName("scanners_run");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_assessment_runs");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_assessment_runs_tenant_id");

                    b.HasIndex("AssessmentId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_assessment_runs_assessment_id_number");

                    b.ToTable("assessment_runs", "atlas");
                });

            modelBuilder.Entity("Atlas.Domain.Assessments.InventorySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assessment_id");

                    b.Property<double>("AverageCyclomaticComplexity")
                        .HasColumnType("double precision")
                        .HasColumnName("average_cyclomatic_complexity");

                    b.Property<string>("CommitSha")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("commit_sha");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("FileCount")
                        .HasColumnType("integer")
                        .HasColumnName("file_count");

                    b.Property<string>("LanguageId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("language_id");

                    b.Property<int>("MaxCyclomaticComplexity")
                        .HasColumnType("integer")
                        .HasColumnName("max_cyclomatic_complexity");

                    b.Property<int>("MethodCount")
                        .HasColumnType("integer")
                        .HasColumnName("method_count");

                    b.Property<int>("ProjectCount")
                        .HasColumnType("integer")
                        .HasColumnName("project_count");

                    b.Property<string>("ProjectsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("projects_json");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<int>("SolutionCount")
                        .HasColumnType("integer")
                        .HasColumnName("solution_count");

                    b.Property<double?>("SymbolResolutionRate")
                        .HasColumnType("double precision")
                        .HasColumnName("symbol_resolution_rate");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TierAchieved")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("tier_achieved");

                    b.Property<long>("TotalLines")
                        .HasColumnType("bigint")
                        .HasColumnName("total_lines");

                    b.Property<int>("TypeCount")
                        .HasColumnType("integer")
                        .HasColumnName("type_count");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_inventory_snapshots");

                    b.HasIndex("RunId")
                        .HasDatabaseName("ix_inventory_snapshots_run_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_inventory_snapshots_tenant_id");

                    b.HasIndex("AssessmentId", "LanguageId", "CreatedAtUtc")
                        .HasDatabaseName("ix_inventory_snapshots_assessment_id_language_id_created_at_utc");

                    b.ToTable("inventory_snapshots", "atlas");
                });

            modelBuilder.Entity("Atlas.Domain.Audit.AuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor");

                    b.Property<Guid?>("AssessmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assessment_id");

                    b.Property<DateTimeOffset>("AtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at_utc");

                    b.Property<string>("ClientIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("client_ip");

                    b.Property<string>("Detail")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("detail");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("method");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("path");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_entries");

                    b.HasIndex("AssessmentId")
                        .HasDatabaseName("ix_audit_entries_assessment_id");

                    b.HasIndex("TenantId", "AtUtc")
                        .HasDatabaseName("ix_audit_entries_tenant_id_at_utc");

                    b.ToTable("audit_entries", "atlas");
                });

            modelBuilder.Entity("Atlas.Domain.Credentials.ConnectorCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<byte[]>("Envelope")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("envelope");

                    b.Property<DateTimeOffset?>("LastUsedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("Username")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_connector_credentials");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_connector_credentials_tenant_id_name");

                    b.ToTable("connector_credentials", "atlas");
                });

            modelBuilder.Entity("Atlas.Domain.Findings.Finding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assessment_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("fingerprint");

                    b.Property<Guid>("FirstSeenScanId")
                        .HasColumnType("uuid")
                        .HasColumnName("first_seen_scan_id");

                    b.Property<Guid>("LastSeenScanId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_seen_scan_id");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("origin");

                    b.Property<Guid?>("ResolvedScanId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_scan_id");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("rule_id");

                    b.Property<int>("Severity")
                        .HasColumnType("integer")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_findings");

                    b.HasIndex("RuleId")
                        .HasDatabaseName("ix_findings_rule_id");

                    b.HasIndex("AssessmentId", "RuleId", "Status")
                        .HasDatabaseName("ix_findings_assessment_id_rule_id_status");

                    b.HasIndex("TenantId", "AssessmentId", "Fingerprint")
                        .IsUnique()
                        .HasDatabaseName("ix_findings_tenant_id_assessment_id_fingerprint");

                    b.ToTable("findings", "atlas");
                });

            modelBuilder.Entity("Atlas.Domain.Findings.FindingOccurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("data_json");

                    b.Property<Guid>("FindingId")
                        .HasColumnType("uuid")
                        .HasColumnName("finding_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("message");

                    b.Property<string>("Remediation")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("remediation");

                    b.Property<Guid>("ScanId")
                        .HasColumnType("uuid")
                        .HasColumnName("scan_id");

                    b.Property<int>("Severity")
                        .HasColumnType("integer")
                        .HasColumnName("severity");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_finding_occurrences");

                    b.HasIndex("ScanId")
                        .HasDatabaseName("ix_finding_occurrences_scan_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_finding_occurrences_tenant_id");

                    b.HasIndex("FindingId", "CreatedAtUtc")
                        .HasDatabaseName("ix_finding_occurrences_finding_id_created_at_utc");

                    b.ToTable("finding_occurrences", "atlas");
                });

            modelBuilder.Entity("Atlas.Domain.Findings.FindingSuppression", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assessment_id");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("author");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<Guid>("FindingId")
                        .HasColumnType("uuid")
                        .HasColumnName("finding_id");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("fingerprint");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("RevokedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("revoked_by");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_finding_suppressions");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_finding_suppressions_tenant_id");

                    b.HasIndex("AssessmentId", "CreatedAtUtc")
                        .HasDatabaseName("ix_finding_suppressions_assessment_id_created_at_utc");

                    b.HasIndex("FindingId", "RevokedAtUtc")
                        .HasDatabaseName("ix_finding_suppressions_finding_id_revoked_at_utc");

                    b.ToTable("finding_suppressions", "atlas");
                });

            modelBuilder.Entity("Atlas.Domain.Findings.SuppressionPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssessmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assessment_id");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("author");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("PathGlob")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("path_glob");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.Property<string>("RulePattern")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("rule_pattern");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_suppression_policies");

                    b.HasIndex("AssessmentId")
                        .HasDatabaseName("ix_suppression_policies_assessment_id");

                    b.HasIndex("TenantId", "AssessmentId")
                        .HasDatabaseName("ix_suppression_policies_tenant_id_assessment_id");

                    b.ToTable("suppression_policies", "atlas");
                });

            modelBuilder.Entity("Atlas.Domain.Health.HealthSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assessment_id");

                    b.Property<string>("CommitSha")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("commit_sha");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DimensionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("dimensions_json");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("explanation");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("model_version");

                    b.Property<int>("OpenFindings")
                        .HasColumnType("integer")
                        .HasColumnName("open_findings");

                    b.Property<int>("ProjectCount")
                        .HasColumnType("integer")
                        .HasColumnName("project_count");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("risk_level");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_health_snapshots");

                    b.HasIndex("RunId")
                        .HasDatabaseName("ix_health_snapshots_run_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_health_snapshots_tenant_id");

                    b.HasIndex("AssessmentId", "CreatedAtUtc")
                        .HasDatabaseName("ix_health_snapshots_assessment_id_created_at_utc");

                    b.ToTable("health_snapshots", "atlas");
                });

            modelBuilder.Entity("Atlas.Domain.Jobs.ScanJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assessment_id");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer")
                        .HasColumnName("attempt");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at_utc");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasDefaultValue("scan")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset?>("LeaseExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at_utc");

                    b.Property<string>("LeasedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("leased_by");

                    b.Property<string>("Payload")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset>("QueuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("queued_at_utc");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_scan_jobs");

                    b.HasIndex("AssessmentId")
                        .HasDatabaseName("ix_scan_jobs_assessment_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_scan_jobs_tenant_id");

                    b.HasIndex("State", "QueuedAtUtc")
                        .HasDatabaseName("ix_scan_jobs_state_queued_at_utc");

                    b.ToTable("scan_jobs", "atlas");
                });

            modelBuilder.Entity("Atlas.Domain.Modernization.ModernizationActual", b =>
                {
                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assessment_id");

                    b.Property<decimal?>("ActualCost")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("actual_cost");

                    b.Property<double>("ActualHours")
                        .HasColumnType("double precision")
                        .HasColumnName("actual_hours");

                    b.Property<double?>("ActualMonths")
                        .HasColumnType("double precision")
                        .HasColumnName("actual_months");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("currency");

                    b.Property<double?>("EstimatedHours")
                        .HasColumnType("double precision")
                        .HasColumnName("estimated_hours");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("notes");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at_utc");

                    b.Property<string>("RecordedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("recorded_by");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("strategy");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("AssessmentId")
                        .HasName("pk_modernization_actuals");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_modernization_actuals_tenant_id");

                    b.ToTable("modernization_actuals", "atlas");
                });

            modelBuilder.Entity("Atlas.Domain.Modernization.TenantCostProfile", b =>
                {
                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("numeric")
                        .HasColumnName("hourly_rate");

                    b.Property<int?>("TeamSize")
                        .HasColumnType("integer")
                        .HasColumnName("team_size");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.HasKey("TenantId")
                        .HasName("pk_tenant_cost_profiles");

                    b.ToTable("tenant_cost_profiles", "atlas");
                });

            modelBuilder.Entity("Atlas.Domain.Rules.RuleDefinition", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("category");

                    b.Property<string>("DefaultSeverity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("default_severity");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<string>("LocalizationsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("localizations_json");

                    b.Property<string>("Remediation")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("remediation");

                    b.Property<string>("ScannerId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("scanner_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_rule_definitions");

                    b.ToTable("rule_definitions", "atlas");
                });

            modelBuilder.Entity("Atlas.Domain.Rules.RuleSeverityOverride", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("RuleId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("rule_id");

                    b.Property<int>("Severity")
                        .HasColumnType("integer")
                        .HasColumnName("severity");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.HasKey("TenantId", "RuleId")
                        .HasName("pk_rule_severity_overrides");

                    b.ToTable("rule_severity_overrides", "atlas");
                });

            modelBuilder.Entity("Atlas.Domain.Scans.Scan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assessment_id");

                    b.Property<string>("CommitSha")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("commit_sha");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error");

                    b.Property<int>("FindingsEmitted")
                        .HasColumnType("integer")
                        .HasColumnName("findings_emitted");

                    b.Property<int>("FindingsNew")
                        .HasColumnType("integer")
                        .HasColumnName("findings_new");

                    b.Property<int>("FindingsRecurring")
                        .HasColumnType("integer")
                        .HasColumnName("findings_recurring");

                    b.Property<int>("FindingsRegressed")
                        .HasColumnType("integer")
                        .HasColumnName("findings_regressed");

                    b.Property<int>("FindingsResolved")
                        .HasColumnType("integer")
                        .HasColumnName("findings_resolved");

                    b.Property<DateTimeOffset?>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at_utc");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("ScannerId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("scanner_id");

                    b.Property<string>("ScannerVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("scanner_version");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_scans");

                    b.HasIndex("RunId")
                        .HasDatabaseName("ix_scans_run_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_scans_tenant_id");

                    b.HasIndex("AssessmentId", "ScannerId", "CommitSha", "Status")
                        .HasDatabaseName("ix_scans_assessment_id_scanner_id_commit_sha_status");

                    b.ToTable("scans", "atlas");
                });

            modelBuilder.Entity("Atlas.Domain.Security.ApiToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash");

                    b.Property<string>("Hint")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("hint");

                    b.Property<DateTimeOffset?>("LastUsedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_api_tokens");

                    b.HasIndex("Hash")
                        .IsUnique()
                        .HasDatabaseName("ix_api_tokens_hash");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_api_tokens_tenant_id");

                    b.ToTable("api_tokens", "atlas");
                });

            modelBuilder.Entity("Atlas.Domain.Tenants.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ExternalKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("ExternalKey")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_external_key");

                    b.ToTable("tenants", "atlas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Default"
                        });
                });

            modelBuilder.Entity("Atlas.Domain.Tenants.TenantNotificationSettings", b =>
                {
                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("DigestDayOfWeek")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("digest_day_of_week");

                    b.Property<int>("DigestHourUtc")
                        .HasColumnType("integer")
                        .HasColumnName("digest_hour_utc");

                    b.Property<string>("Secret")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("secret");

                    b.Property<string>("SlackWebhookUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("slack_webhook_url");

                    b.Property<string>("TeamsWebhookUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("teams_webhook_url");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.Property<string>("WebhookUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("webhook_url");

                    b.HasKey("TenantId")
                        .HasName("pk_tenant_notification_settings");

                    b.ToTable("tenant_notification_settings", "atlas");
                });

            modelBuilder.Entity("Atlas.Domain.Workspaces.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Branch")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("branch");

                    b.Property<string>("CommitSha")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("commit_sha");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("failure_reason");

                    b.Property<bool>("IsBorrowed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_borrowed");

                    b.Property<DateTimeOffset>("LeaseExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at_utc");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("root_path");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_kind");

                    b.Property<string>("SourceLocator")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("source_locator");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_workspaces");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_workspaces_tenant_id");

                    b.HasIndex("State", "LeaseExpiresAtUtc")
                        .HasDatabaseName("ix_workspaces_state_lease_expires_at_utc");

                    b.ToTable("workspaces", "atlas");
                });

            modelBuilder.Entity("Atlas.Domain.Ai.AiNarrative", b =>
                {
                    b.HasOne("Atlas.Domain.Assessments.Assessment", null)
                        .WithMany()
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ai_narratives_assessments_assessment_id");

                    b.HasOne("Atlas.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ai_narratives_tenants_tenant_id");
                });

            modelBuilder.Entity("Atlas.Domain.Ai.AiProviderSettings", b =>
                {
                    b.HasOne("Atlas.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ai_provider_settings_tenants_tenant_id");
                });

            modelBuilder.Entity("Atlas.Domain.Ai.BusinessRule", b =>
                {
                    b.HasOne("Atlas.Domain.Ai.BusinessRuleAnalysis", null)
                        .WithMany()
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_business_rules_business_rule_analyses_analysis_id");

                    b.HasOne("Atlas.Domain.Assessments.Assessment", null)
                        .WithMany()
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_business_rules_assessments_assessment_id");

                    b.HasOne("Atlas.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_business_rules_tenants_tenant_id");
                });

            modelBuilder.Entity("Atlas.Domain.Ai.BusinessRuleAnalysis", b =>
                {
                    b.HasOne("Atlas.Domain.Assessments.Assessment", null)
                        .WithMany()
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_business_rule_analyses_assessments_assessment_id");

                    b.HasOne("Atlas.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_business_rule_analyses_tenants_tenant_id");
                });

            modelBuilder.Entity("Atlas.Domain.Assessments.Assessment", b =>
                {
                    b.HasOne("Atlas.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assessments_tenants_tenant_id");
                });

            modelBuilder.Entity("Atlas.Domain.Assessments.AssessmentAccess", b =>
                {
                    b.HasOne("Atlas.Domain.Assessments.Assessment", null)
                        .WithMany()
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assessment_access_assessments_assessment_id");

                    b.HasOne("Atlas.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assessment_access_tenants_tenant_id");
                });

            modelBuilder.Entity("Atlas.Domain.Assessments.AssessmentRun", b =>
                {
                    b.HasOne("Atlas.Domain.Assessments.Assessment", null)
                        .WithMany()
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assessment_runs_assessments_assessment_id");

                    b.HasOne("Atlas.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assessment_runs_tenants_tenant_id");
                });

            modelBuilder.Entity("Atlas.Domain.Assessments.InventorySnapshot", b =>
                {
                    b.HasOne("Atlas.Domain.Assessments.Assessment", null)
                        .WithMany()
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_snapshots_assessments_assessment_id");

                    b.HasOne("Atlas.Domain.Assessments.AssessmentRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .HasConstraintName("fk_inventory_snapshots_assessment_runs_run_id");

                    b.HasOne("Atlas.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_snapshots_tenants_tenant_id");
                });

            modelBuilder.Entity("Atlas.Domain.Credentials.ConnectorCredential", b =>
                {
                    b.HasOne("Atlas.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_connector_credentials_tenants_tenant_id");
                });

            modelBuilder.Entity("Atlas.Domain.Findings.Finding", b =>
                {
                    b.HasOne("Atlas.Domain.Assessments.Assessment", null)
                        .WithMany()
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_findings_assessments_assessment_id");

                    b.HasOne("Atlas.Domain.Rules.RuleDefinition", null)
                        .WithMany()
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_findings_rule_definitions_rule_id");

                    b.HasOne("Atlas.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_findings_tenants_tenant_id");
                });

            modelBuilder.Entity("Atlas.Domain.Findings.FindingOccurrence", b =>
                {
                    b.HasOne("Atlas.Domain.Findings.Finding", null)
                        .WithMany()
                        .HasForeignKey("FindingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_finding_occurrences_findings_finding_id");

                    b.HasOne("Atlas.Domain.Scans.Scan", null)
                        .WithMany()
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_finding_occurrences_scans_scan_id");

                    b.HasOne("Atlas.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_finding_occurrences_tenants_tenant_id");

                    b.OwnsOne("Atlas.Domain.Findings.Evidence", "Evidence", b1 =>
                        {
                            b1.Property<Guid>("FindingOccurrenceId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("FilePath")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("evidence_file_path");

                            b1.Property<int?>("LineEnd")
                                .HasColumnType("integer")
                                .HasColumnName("evidence_line_end");

                            b1.Property<int?>("LineStart")
                                .HasColumnType("integer")
                                .HasColumnName("evidence_line_start");

                            b1.Property<string>("ScannerId")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("evidence_scanner_id");

                            b1.Property<string>("ScannerVersion")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("evidence_scanner_version");

                            b1.Property<string>("SnippetHash")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("evidence_snippet_hash");

                            b1.Property<string>("Symbol")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("evidence_symbol");

                            b1.HasKey("FindingOccurrenceId");

                            b1.ToTable("finding_occurrences", "atlas");

                            b1.WithOwner()
                                .HasForeignKey("FindingOccurrenceId")
                                .HasConstraintName("fk_finding_occurrences_finding_occurrences_id");
                        });

                    b.Navigation("Evidence")
                        .IsRequired();
                });

            modelBuilder.Entity("Atlas.Domain.Findings.FindingSuppression", b =>
                {
                    b.HasOne("Atlas.Domain.Assessments.Assessment", null)
                        .WithMany()
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_finding_suppressions_assessments_assessment_id");

                    b.HasOne("Atlas.Domain.Findings.Finding", null)
                        .WithMany()
                        .HasForeignKey("FindingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_finding_suppressions_findings_finding_id");

                    b.HasOne("Atlas.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_finding_suppressions_tenants_tenant_id");
                });

            modelBuilder.Entity("Atlas.Domain.Findings.SuppressionPolicy", b =>
                {
                    b.HasOne("Atlas.Domain.Assessments.Assessment", null)
                        .WithMany()
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_suppression_policies_assessments_assessment_id");

                    b.HasOne("Atlas.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_suppression_policies_tenants_tenant_id");
                });

            modelBuilder.Entity("Atlas.Domain.Health.HealthSnapshot", b =>
                {
                    b.HasOne("Atlas.Domain.Assessments.Assessment", null)
                        .WithMany()
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_health_snapshots_assessments_assessment_id");

                    b.HasOne("Atlas.Domain.Assessments.AssessmentRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .HasConstraintName("fk_health_snapshots_assessment_runs_run_id");

                    b.HasOne("Atlas.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_health_snapshots_tenants_tenant_id");
                });

            modelBuilder.Entity("Atlas.Domain.Jobs.ScanJob", b =>
                {
                    b.HasOne("Atlas.Domain.Assessments.Assessment", null)
                        .WithMany()
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scan_jobs_assessments_assessment_id");

                    b.HasOne("Atlas.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scan_jobs_tenants_tenant_id");
                });

            modelBuilder.Entity("Atlas.Domain.Modernization.ModernizationActual", b =>
                {
                    b.HasOne("Atlas.Domain.Assessments.Assessment", null)
                        .WithOne()
                        .HasForeignKey("Atlas.Domain.Modernization.ModernizationActual", "AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_modernization_actuals_assessments_assessment_id");

                    b.HasOne("Atlas.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_modernization_actuals_tenants_tenant_id");
                });

            modelBuilder.Entity("Atlas.Domain.Scans.Scan", b =>
                {
                    b.HasOne("Atlas.Domain.Assessments.Assessment", null)
                        .WithMany()
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scans_assessments_assessment_id");

                    b.HasOne("Atlas.Domain.Assessments.AssessmentRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .HasConstraintName("fk_scans_assessment_runs_run_id");

                    b.HasOne("Atlas.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scans_tenants_tenant_id");
                });

            modelBuilder.Entity("Atlas.Domain.Security.ApiToken", b =>
                {
                    b.HasOne("Atlas.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_api_tokens_tenants_tenant_id");
                });

            modelBuilder.Entity("Atlas.Domain.Workspaces.Workspace", b =>
                {
                    b.HasOne("Atlas.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workspaces_tenants_tenant_id");
                });
#pragma warning restore 612, 618
        }
    }
}
